version: "3"

services:
  tests: &tests
    image: keboola/syrup-php-client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KBDP_API_URL
      - KBDP_USERNAME
      - KBDP_PASSWORD
      - KBDP_VENDOR
    volumes:
      - ./build/logs/:/code/build/logs/
  dev:
    <<: *tests
    volumes:
      - .:/code
